### ISSUE TITLE
5.1的解包还没来么

### ISSUE THREAD

**Issue by jiongjiongJOJO** [YuehaiTeam/amos-data#1]
如题
![Clip_2024-10-09_11-54-27](https://github.com/user-attachments/assets/8d2d85c2-04c5-4758-a2ed-390604417473)

**Comment by BTMuli** [comment]
![Screenshot_20241009_133021_com.tencent.mobileqq.png](https://github.com/user-attachments/assets/8bb4b7f5-3c8a-47fa-a1c4-2184bbb99762)

**Comment by jiongjiongJOJO** [comment]
> ![Screenshot_20241009_133021_com.tencent.mobileqq.png](https://private-user-images.githubusercontent.com/72692909/374816746-8bb4b7f5-3c8a-47fa-a1c4-2184bbb99762.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NTIyMDMsIm5iZiI6MTcyODQ1MTkwMywicGF0aCI6Ii83MjY5MjkwOS8zNzQ4MTY3NDYtOGJiNGI3ZjUtM2M4YS00N2ZhLWExYzQtMjE4NGJiYjk5NzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA1MzE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZmZiZDY5YTI0NmI1ZTliNjg0MjdlMWJmODU0NDljYjA2NWUwYmNjOTkxYjgzMmM5OWJiMDZkMmFkODA0ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LogkZP6P5nNsekAbVwxb9fO5GZrz2x1wjtKulK1Ges4)

还有群，发下群号呗😋😋
